
package maildetection;

/**
 *
 * @author saurabh
 */

import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class ShowForum extends javax.swing.JFrame {
frmConnection frm=new frmConnection();
Statement st=null;
Statement st1=null;
ResultSet rs=null;
ResultSet rs1=null;
Statement st2=null;
ResultSet rs2=null;
String[][] rows;

String uname="";
String[] columns=new String[]{"S.No.","Message","User","Likes","Comments","Message ID"};

    DefaultTableModel tableData;
    
    public ShowForum(String uname) {
        initComponents();
                this.uname=uname;
                init();
            
    }
    
    
    public void init()
    {
        int count=0;
        int count1=0;
        int i=0;
         try
        {
            st=frm.getCon().createStatement();
            st1=frm.getCon().createStatement();
            st2=frm.getCon().createStatement();
            tableData=new DefaultTableModel(rows,columns);
            jTable1.getModel();
            rs=st.executeQuery("select * from forum order by id");
            while(rs.next())
            {
                i++;
                rs1=st1.executeQuery("select * from forum_likes where msg_id="+rs.getInt("id"));
                while(rs1.next())
                {
                   count++; 
                }
                rs2=st2.executeQuery("select * from forum_comments where msg_id="+rs.getInt("id"));
                while(rs2.next())
                {
                   count1++; 
                }
                Object[] x={i,rs.getString("msg"),rs.getString("uname"),count,count1,rs.getString("id")};
                tableData.addRow(x);
                count=0;
                count1=0;
                
            }
            jTable1.setModel(tableData);
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forum Module");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("Comment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 420, 120, 24);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-delete.gif"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 290, 150, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 70, 520, 320);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        jButton3.setText("Comment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 410, 150, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create_new.png"))); // NOI18N
        jButton4.setText("Create New");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 80, 150, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        jButton5.setText("Show Comment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 130, 150, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/like_icon_1.png"))); // NOI18N
        jButton6.setText("Show Likes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(580, 180, 150, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/like_icon_1.png"))); // NOI18N
        jButton7.setText("Like");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(580, 230, 150, 40);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setText("user forum");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 30, 250, 24);
        jPanel1.add(txtComment);
        txtComment.setBounds(140, 410, 430, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String str=jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5).toString();
        int mid= Integer.parseInt(str);
        try
        {
     st=frm.getCon().createStatement();
     
         st.execute("insert into forum_comments(msg_id,uname,comment1) values("+mid
                 +",'"+uname+"','"+txtComment.getText()+"')");
     
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        init();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CreateNew(uname).setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String str=jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5).toString();
        int mid= Integer.parseInt(str);
        new ShowForumComments(mid).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String str=jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5).toString();
        int mid= Integer.parseInt(str);
        new ShowForumLikes(mid).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String str=jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5).toString();
        int mid= Integer.parseInt(str);
        try
        {
     st=frm.getCon().createStatement();
     
         st.execute("insert into forum_likes(msg_id,uname) values("+mid
                 +",'"+uname+"')");
     
     
        }
        catch(Exception ex){}
        init();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtComment;
    // End of variables declaration//GEN-END:variables

}
